### ISSUE TITLE
在某个版本后无法使用Watchtower自动更新Docker镜像

### ISSUE THREAD

**Issue by TheRealKamisama** [alist-org/alist#3183]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

xhofe/alist:latest

### Driver used / 使用的存储驱动

非相关

### Describe the bug / 问题描述

```
Could not do a head request for "xhofe/alist:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
```
从某个版本后Watchtower一直在失败, 大概观察第一次出现在1月27日  
调查后发现Watchtower那边已经统计了只有几个镜像有这样的问题, 并且已经分析了问题原因, 详细信息在链接里:  
https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053  
Pihole好像找到了办法从他们的镜像那边解决这个问题, 我没有细看, 请问能不能看看Alist这边是不是也可以一样解决?

### Reproduction / 复现链接

https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053

**Comment by Xhofe** [comment]
According to your reference, don't use a really short interval for watchtower due to the docker API rate limiting is a better solution instead of change original image. In that case you can set the WATCHTOWER_WARN_ON_HEAD_FAILURE=never environment variable for watchtower, or add the equivalent argument --warn-on-head-failure never (see https://containrrr.dev/watchtower/arguments/#head_failure_warnings).
