### ISSUE TITLE
复制文件到本地存储时出现Bad Record Mac错误

### ISSUE THREAD

**Issue by honmaple** [alist-org/alist#4672]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.19.0

### Driver used / 使用的存储驱动

阿里云Open

### Describe the bug / 问题描述

复制阿里云Open的文件到本地存储，总是出现`local error: tls: bad record MAC`，仅在复制大文件(30GB+)时偶尔出现，文件越大，出现的概率越高

- 阿里云Open的设置
  <img width="975" alt="image" src="https://github.com/alist-org/alist/assets/12235570/294d57f5-1b18-46b4-afbc-6221ac112942">
- 本地存储的设置
  <img width="1939" alt="image" src="https://github.com/alist-org/alist/assets/12235570/93a139f9-ddc1-4c37-87bb-6f524576f2a8">

另外，能否支持分片下载或者复制，每次复制出错后都要从头开始下载

### Reproduction / 复现链接

无

**Comment by Xhofe** [comment]
If you are getting a lot of bad packets due to some fault in your network it can happen that a bad packet will at random survive the 32-bit TCP checksum. About 1 in 4 billion bad packets will slip by TCP. Once this packet is delivered to SSL it will generate a bad record MAC for sure, because the SSL Mac is 96 bits in size.

If this is the cause, the only solution is improve the network.

Note that, in general, this is a very unlikely cause of a bad record MAC. Even a network with faulty hardware that generates bad packets is unlikely to generate them with correct IP and TCP metadata such that the packets are actually passed to the socket corresponding to the TLS connection.

references: https://stackoverflow.com/questions/8154617/how-to-troubleshoot-ssl-bad-record-mac-exception
